### PR TITLE
fixing compile error

### PR DESCRIPTION
**Pull request by rotzbouf**
Fixing compile error: src/net.cpp:60:1: error: reference to ‘array’ is ambiguous

### CODE REVIEW

**Comment by joelao95** [comment]
I saw some C++11 warnings in your compiling; what's your version of Qt? Could you try compiling without C++11 enabled? Basically C++11 is not tested and well supported so far.

**Comment by rotzbouf** [comment]
As default I have the version:
QMake version 3.1
Using Qt version 5.8.0 in /usr/lib

But I do still have QT4 around in case I run into problems with the 5.

Modified the Makefile which was generated by qmake to try without C++11
CXX = g++ -std=c++0x

**Comment by rotzbouf** [comment]
Ok, so both tests failed.
I tried:
$ qmake-qt4
$ make

and
$ qmake-qt5
$ make

both times modified the CXXFLAG to -std=c++0x
I guess it failed due to thc gcc version used. (gcc (GCC) 6.3.1 20170109)

When compiling without additional flags and by using QT5, I have lot of compile warnings related to C++11 but the build suceeds. The wallet also starts up afterwards and syncs.

**Comment by joelao95** [comment]
Starting from Qt5.7, c++11 is enabled by default. Qt5.5 without c++11 has been used so far for official release. In either way, I'll test out your merge request. Thanks.

**Comment by flok99** [comment]
I can confirm that rotzbouf's fix is the right one.

**Pull request merged**
